name: Application build and deploy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Application build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@pages
      - name: Set up Node.js
        uses: actions/setup-node@pages
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build React application
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@pages
        with:
          name: build-artifact
          path: build
      - name: Docker Hub auth
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/studentmanagerfrontend:latest
